version: '3.9'
services:
  api-adapter:
    build:
      context: ./api-adapter
      network: host
    ports:
      - 3000:3000
    privileged: true
  web:
    build:
      context: ./web
      network: host
    ports:
      - 80:80

